### ISSUE TITLE
'hash_value': identifier not found

### ISSUE THREAD

**Issue by oliverportcnc** [boostorg/url#892] opened 2024-12-19 14:29 UTC
This error occurs both in MSVC and in GCC, just with slightly different error messages.

See [https://github.com/boostorg/boost/issues/991](https://github.com/boostorg/boost/issues/991) for more details.

This can be fixed by adding

`#include <boost/container_hash/hash.hpp>`

inside `string_view_base.hpp`.

**Comment by alandefreitas** [comment] 2024-12-19 14:52
Mmm... Then Boost.URL would depend on ContainerHash.

The problem here is that you're using a Boost release where `hash_value` had already been removed from `core::string_view` but hasn't been removed yet from Boost.URL.

The problem should have been fixed already since https://github.com/boostorg/url/commit/428ea43f40790b84c59b0792fe2e8abccdf2f558 has been merged in `master`.

**Comment by oliverportcnc** [comment] 2024-12-19 14:58
Thanks. This issue is still somehow present in Boost master though as shown in the linked ticket?

**Comment by alandefreitas** [comment] 2024-12-19 20:03
Have you tested this more recently? The issue is from 3 days ago and the develop branch has been merged to master yesterday.

**Comment by seektechnz** [comment] 2024-12-20 00:08
Seems to be working fine now on the same codebase as the OP, thanks.

**Closed** 2024-12-20 03:07 UTC
